# Generated by Django 3.2.6 on 2021-08-29 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_searchhistory_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchhistory',
            old_name='count',
            new_name='keyword_count',
        ),
    ]
