# Generated by Django 3.2.6 on 2021-08-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210829_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchhistory',
            name='keyword_count_by_user',
            field=models.IntegerField(default=1),
        ),
    ]
